# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Sariely\Downloads\Reisim-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Sariely\Downloads\Reisim-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Sariely\Downloads\Reisim-master\CMakeFiles C:\Users\Sariely\Downloads\Reisim-master\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Sariely\Downloads\Reisim-master\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LANGUAGES

# Build rule for target.
LANGUAGES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 LANGUAGES
.PHONY : LANGUAGES

# fast build rule for target.
LANGUAGES/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/build
.PHONY : LANGUAGES/fast

#=============================================================================
# Target rules for targets named LANGUAGES_autogen_timestamp_deps

# Build rule for target.
LANGUAGES_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 LANGUAGES_autogen_timestamp_deps
.PHONY : LANGUAGES_autogen_timestamp_deps

# fast build rule for target.
LANGUAGES_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES_autogen_timestamp_deps.dir\build.make CMakeFiles/LANGUAGES_autogen_timestamp_deps.dir/build
.PHONY : LANGUAGES_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named LANGUAGES_autogen

# Build rule for target.
LANGUAGES_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 LANGUAGES_autogen
.PHONY : LANGUAGES_autogen

# fast build rule for target.
LANGUAGES_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES_autogen.dir\build.make CMakeFiles/LANGUAGES_autogen.dir/build
.PHONY : LANGUAGES_autogen/fast

LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.obj: LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.obj
.PHONY : LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.obj

# target to build an object file
LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.obj
.PHONY : LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.obj

LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.i: LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.i
.PHONY : LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.i

# target to preprocess a source file
LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.i
.PHONY : LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.i

LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.s: LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.s
.PHONY : LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.s

# target to generate assembly for a file
LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.s
.PHONY : LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.cpp.s

LANGUAGES_autogen/mocs_compilation.obj: LANGUAGES_autogen/mocs_compilation.cpp.obj
.PHONY : LANGUAGES_autogen/mocs_compilation.obj

# target to build an object file
LANGUAGES_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/LANGUAGES_autogen/mocs_compilation.cpp.obj
.PHONY : LANGUAGES_autogen/mocs_compilation.cpp.obj

LANGUAGES_autogen/mocs_compilation.i: LANGUAGES_autogen/mocs_compilation.cpp.i
.PHONY : LANGUAGES_autogen/mocs_compilation.i

# target to preprocess a source file
LANGUAGES_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/LANGUAGES_autogen/mocs_compilation.cpp.i
.PHONY : LANGUAGES_autogen/mocs_compilation.cpp.i

LANGUAGES_autogen/mocs_compilation.s: LANGUAGES_autogen/mocs_compilation.cpp.s
.PHONY : LANGUAGES_autogen/mocs_compilation.s

# target to generate assembly for a file
LANGUAGES_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/LANGUAGES_autogen/mocs_compilation.cpp.s
.PHONY : LANGUAGES_autogen/mocs_compilation.cpp.s

src/agent.obj: src/agent.cpp.obj
.PHONY : src/agent.obj

# target to build an object file
src/agent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent.cpp.obj
.PHONY : src/agent.cpp.obj

src/agent.i: src/agent.cpp.i
.PHONY : src/agent.i

# target to preprocess a source file
src/agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent.cpp.i
.PHONY : src/agent.cpp.i

src/agent.s: src/agent.cpp.s
.PHONY : src/agent.s

# target to generate assembly for a file
src/agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent.cpp.s
.PHONY : src/agent.cpp.s

src/agent_control.obj: src/agent_control.cpp.obj
.PHONY : src/agent_control.obj

# target to build an object file
src/agent_control.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_control.cpp.obj
.PHONY : src/agent_control.cpp.obj

src/agent_control.i: src/agent_control.cpp.i
.PHONY : src/agent_control.i

# target to preprocess a source file
src/agent_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_control.cpp.i
.PHONY : src/agent_control.cpp.i

src/agent_control.s: src/agent_control.cpp.s
.PHONY : src/agent_control.s

# target to generate assembly for a file
src/agent_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_control.cpp.s
.PHONY : src/agent_control.cpp.s

src/agent_hazardidentification.obj: src/agent_hazardidentification.cpp.obj
.PHONY : src/agent_hazardidentification.obj

# target to build an object file
src/agent_hazardidentification.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_hazardidentification.cpp.obj
.PHONY : src/agent_hazardidentification.cpp.obj

src/agent_hazardidentification.i: src/agent_hazardidentification.cpp.i
.PHONY : src/agent_hazardidentification.i

# target to preprocess a source file
src/agent_hazardidentification.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_hazardidentification.cpp.i
.PHONY : src/agent_hazardidentification.cpp.i

src/agent_hazardidentification.s: src/agent_hazardidentification.cpp.s
.PHONY : src/agent_hazardidentification.s

# target to generate assembly for a file
src/agent_hazardidentification.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_hazardidentification.cpp.s
.PHONY : src/agent_hazardidentification.cpp.s

src/agent_move.obj: src/agent_move.cpp.obj
.PHONY : src/agent_move.obj

# target to build an object file
src/agent_move.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_move.cpp.obj
.PHONY : src/agent_move.cpp.obj

src/agent_move.i: src/agent_move.cpp.i
.PHONY : src/agent_move.i

# target to preprocess a source file
src/agent_move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_move.cpp.i
.PHONY : src/agent_move.cpp.i

src/agent_move.s: src/agent_move.cpp.s
.PHONY : src/agent_move.s

# target to generate assembly for a file
src/agent_move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_move.cpp.s
.PHONY : src/agent_move.cpp.s

src/agent_perception.obj: src/agent_perception.cpp.obj
.PHONY : src/agent_perception.obj

# target to build an object file
src/agent_perception.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_perception.cpp.obj
.PHONY : src/agent_perception.cpp.obj

src/agent_perception.i: src/agent_perception.cpp.i
.PHONY : src/agent_perception.i

# target to preprocess a source file
src/agent_perception.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_perception.cpp.i
.PHONY : src/agent_perception.cpp.i

src/agent_perception.s: src/agent_perception.cpp.s
.PHONY : src/agent_perception.s

# target to generate assembly for a file
src/agent_perception.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_perception.cpp.s
.PHONY : src/agent_perception.cpp.s

src/agent_recognition.obj: src/agent_recognition.cpp.obj
.PHONY : src/agent_recognition.obj

# target to build an object file
src/agent_recognition.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_recognition.cpp.obj
.PHONY : src/agent_recognition.cpp.obj

src/agent_recognition.i: src/agent_recognition.cpp.i
.PHONY : src/agent_recognition.i

# target to preprocess a source file
src/agent_recognition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_recognition.cpp.i
.PHONY : src/agent_recognition.cpp.i

src/agent_recognition.s: src/agent_recognition.cpp.s
.PHONY : src/agent_recognition.s

# target to generate assembly for a file
src/agent_recognition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_recognition.cpp.s
.PHONY : src/agent_recognition.cpp.s

src/agent_riskevaluation.obj: src/agent_riskevaluation.cpp.obj
.PHONY : src/agent_riskevaluation.obj

# target to build an object file
src/agent_riskevaluation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_riskevaluation.cpp.obj
.PHONY : src/agent_riskevaluation.cpp.obj

src/agent_riskevaluation.i: src/agent_riskevaluation.cpp.i
.PHONY : src/agent_riskevaluation.i

# target to preprocess a source file
src/agent_riskevaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_riskevaluation.cpp.i
.PHONY : src/agent_riskevaluation.cpp.i

src/agent_riskevaluation.s: src/agent_riskevaluation.cpp.s
.PHONY : src/agent_riskevaluation.s

# target to generate assembly for a file
src/agent_riskevaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_riskevaluation.cpp.s
.PHONY : src/agent_riskevaluation.cpp.s

src/agent_route_management.obj: src/agent_route_management.cpp.obj
.PHONY : src/agent_route_management.obj

# target to build an object file
src/agent_route_management.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_route_management.cpp.obj
.PHONY : src/agent_route_management.cpp.obj

src/agent_route_management.i: src/agent_route_management.cpp.i
.PHONY : src/agent_route_management.i

# target to preprocess a source file
src/agent_route_management.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_route_management.cpp.i
.PHONY : src/agent_route_management.cpp.i

src/agent_route_management.s: src/agent_route_management.cpp.s
.PHONY : src/agent_route_management.s

# target to generate assembly for a file
src/agent_route_management.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/agent_route_management.cpp.s
.PHONY : src/agent_route_management.cpp.s

src/caldistributethread.obj: src/caldistributethread.cpp.obj
.PHONY : src/caldistributethread.obj

# target to build an object file
src/caldistributethread.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/caldistributethread.cpp.obj
.PHONY : src/caldistributethread.cpp.obj

src/caldistributethread.i: src/caldistributethread.cpp.i
.PHONY : src/caldistributethread.i

# target to preprocess a source file
src/caldistributethread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/caldistributethread.cpp.i
.PHONY : src/caldistributethread.cpp.i

src/caldistributethread.s: src/caldistributethread.cpp.s
.PHONY : src/caldistributethread.s

# target to generate assembly for a file
src/caldistributethread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/caldistributethread.cpp.s
.PHONY : src/caldistributethread.cpp.s

src/configwindow.obj: src/configwindow.cpp.obj
.PHONY : src/configwindow.obj

# target to build an object file
src/configwindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/configwindow.cpp.obj
.PHONY : src/configwindow.cpp.obj

src/configwindow.i: src/configwindow.cpp.i
.PHONY : src/configwindow.i

# target to preprocess a source file
src/configwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/configwindow.cpp.i
.PHONY : src/configwindow.cpp.i

src/configwindow.s: src/configwindow.cpp.s
.PHONY : src/configwindow.s

# target to generate assembly for a file
src/configwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/configwindow.cpp.s
.PHONY : src/configwindow.cpp.s

src/eventmanager.obj: src/eventmanager.cpp.obj
.PHONY : src/eventmanager.obj

# target to build an object file
src/eventmanager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/eventmanager.cpp.obj
.PHONY : src/eventmanager.cpp.obj

src/eventmanager.i: src/eventmanager.cpp.i
.PHONY : src/eventmanager.i

# target to preprocess a source file
src/eventmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/eventmanager.cpp.i
.PHONY : src/eventmanager.cpp.i

src/eventmanager.s: src/eventmanager.cpp.s
.PHONY : src/eventmanager.s

# target to generate assembly for a file
src/eventmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/eventmanager.cpp.s
.PHONY : src/eventmanager.cpp.s

src/gltransform3d.obj: src/gltransform3d.cpp.obj
.PHONY : src/gltransform3d.obj

# target to build an object file
src/gltransform3d.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/gltransform3d.cpp.obj
.PHONY : src/gltransform3d.cpp.obj

src/gltransform3d.i: src/gltransform3d.cpp.i
.PHONY : src/gltransform3d.i

# target to preprocess a source file
src/gltransform3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/gltransform3d.cpp.i
.PHONY : src/gltransform3d.cpp.i

src/gltransform3d.s: src/gltransform3d.cpp.s
.PHONY : src/gltransform3d.s

# target to generate assembly for a file
src/gltransform3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/gltransform3d.cpp.s
.PHONY : src/gltransform3d.cpp.s

src/graphiccanvas.obj: src/graphiccanvas.cpp.obj
.PHONY : src/graphiccanvas.obj

# target to build an object file
src/graphiccanvas.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/graphiccanvas.cpp.obj
.PHONY : src/graphiccanvas.cpp.obj

src/graphiccanvas.i: src/graphiccanvas.cpp.i
.PHONY : src/graphiccanvas.i

# target to preprocess a source file
src/graphiccanvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/graphiccanvas.cpp.i
.PHONY : src/graphiccanvas.cpp.i

src/graphiccanvas.s: src/graphiccanvas.cpp.s
.PHONY : src/graphiccanvas.s

# target to generate assembly for a file
src/graphiccanvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/graphiccanvas.cpp.s
.PHONY : src/graphiccanvas.cpp.s

src/logoutputthread.obj: src/logoutputthread.cpp.obj
.PHONY : src/logoutputthread.obj

# target to build an object file
src/logoutputthread.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/logoutputthread.cpp.obj
.PHONY : src/logoutputthread.cpp.obj

src/logoutputthread.i: src/logoutputthread.cpp.i
.PHONY : src/logoutputthread.i

# target to preprocess a source file
src/logoutputthread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/logoutputthread.cpp.i
.PHONY : src/logoutputthread.cpp.i

src/logoutputthread.s: src/logoutputthread.cpp.s
.PHONY : src/logoutputthread.s

# target to generate assembly for a file
src/logoutputthread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/logoutputthread.cpp.s
.PHONY : src/logoutputthread.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.obj: src/mainwindow.cpp.obj
.PHONY : src/mainwindow.obj

# target to build an object file
src/mainwindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/mainwindow.cpp.obj
.PHONY : src/mainwindow.cpp.obj

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/networkdrivecheck.obj: src/networkdrivecheck.cpp.obj
.PHONY : src/networkdrivecheck.obj

# target to build an object file
src/networkdrivecheck.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/networkdrivecheck.cpp.obj
.PHONY : src/networkdrivecheck.cpp.obj

src/networkdrivecheck.i: src/networkdrivecheck.cpp.i
.PHONY : src/networkdrivecheck.i

# target to preprocess a source file
src/networkdrivecheck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/networkdrivecheck.cpp.i
.PHONY : src/networkdrivecheck.cpp.i

src/networkdrivecheck.s: src/networkdrivecheck.cpp.s
.PHONY : src/networkdrivecheck.s

# target to generate assembly for a file
src/networkdrivecheck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/networkdrivecheck.cpp.s
.PHONY : src/networkdrivecheck.cpp.s

src/randomgenerator.obj: src/randomgenerator.cpp.obj
.PHONY : src/randomgenerator.obj

# target to build an object file
src/randomgenerator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/randomgenerator.cpp.obj
.PHONY : src/randomgenerator.cpp.obj

src/randomgenerator.i: src/randomgenerator.cpp.i
.PHONY : src/randomgenerator.i

# target to preprocess a source file
src/randomgenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/randomgenerator.cpp.i
.PHONY : src/randomgenerator.cpp.i

src/randomgenerator.s: src/randomgenerator.cpp.s
.PHONY : src/randomgenerator.s

# target to generate assembly for a file
src/randomgenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/randomgenerator.cpp.s
.PHONY : src/randomgenerator.cpp.s

src/resim.obj: src/resim.rc.obj
.PHONY : src/resim.obj

# target to build an object file
src/resim.rc.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/resim.rc.obj
.PHONY : src/resim.rc.obj

src/road.obj: src/road.cpp.obj
.PHONY : src/road.obj

# target to build an object file
src/road.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/road.cpp.obj
.PHONY : src/road.cpp.obj

src/road.i: src/road.cpp.i
.PHONY : src/road.i

# target to preprocess a source file
src/road.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/road.cpp.i
.PHONY : src/road.cpp.i

src/road.s: src/road.cpp.s
.PHONY : src/road.s

# target to generate assembly for a file
src/road.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/road.cpp.s
.PHONY : src/road.cpp.s

src/road_path_calc.obj: src/road_path_calc.cpp.obj
.PHONY : src/road_path_calc.obj

# target to build an object file
src/road_path_calc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/road_path_calc.cpp.obj
.PHONY : src/road_path_calc.cpp.obj

src/road_path_calc.i: src/road_path_calc.cpp.i
.PHONY : src/road_path_calc.i

# target to preprocess a source file
src/road_path_calc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/road_path_calc.cpp.i
.PHONY : src/road_path_calc.cpp.i

src/road_path_calc.s: src/road_path_calc.cpp.s
.PHONY : src/road_path_calc.s

# target to generate assembly for a file
src/road_path_calc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/road_path_calc.cpp.s
.PHONY : src/road_path_calc.cpp.s

src/scenario.obj: src/scenario.cpp.obj
.PHONY : src/scenario.obj

# target to build an object file
src/scenario.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/scenario.cpp.obj
.PHONY : src/scenario.cpp.obj

src/scenario.i: src/scenario.cpp.i
.PHONY : src/scenario.i

# target to preprocess a source file
src/scenario.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/scenario.cpp.i
.PHONY : src/scenario.cpp.i

src/scenario.s: src/scenario.cpp.s
.PHONY : src/scenario.s

# target to generate assembly for a file
src/scenario.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/scenario.cpp.s
.PHONY : src/scenario.cpp.s

src/simulationmanager.obj: src/simulationmanager.cpp.obj
.PHONY : src/simulationmanager.obj

# target to build an object file
src/simulationmanager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/simulationmanager.cpp.obj
.PHONY : src/simulationmanager.cpp.obj

src/simulationmanager.i: src/simulationmanager.cpp.i
.PHONY : src/simulationmanager.i

# target to preprocess a source file
src/simulationmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/simulationmanager.cpp.i
.PHONY : src/simulationmanager.cpp.i

src/simulationmanager.s: src/simulationmanager.cpp.s
.PHONY : src/simulationmanager.s

# target to generate assembly for a file
src/simulationmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/simulationmanager.cpp.s
.PHONY : src/simulationmanager.cpp.s

src/system_snapshot.obj: src/system_snapshot.cpp.obj
.PHONY : src/system_snapshot.obj

# target to build an object file
src/system_snapshot.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/system_snapshot.cpp.obj
.PHONY : src/system_snapshot.cpp.obj

src/system_snapshot.i: src/system_snapshot.cpp.i
.PHONY : src/system_snapshot.i

# target to preprocess a source file
src/system_snapshot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/system_snapshot.cpp.i
.PHONY : src/system_snapshot.cpp.i

src/system_snapshot.s: src/system_snapshot.cpp.s
.PHONY : src/system_snapshot.s

# target to generate assembly for a file
src/system_snapshot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/system_snapshot.cpp.s
.PHONY : src/system_snapshot.cpp.s

src/systemthread.obj: src/systemthread.cpp.obj
.PHONY : src/systemthread.obj

# target to build an object file
src/systemthread.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/systemthread.cpp.obj
.PHONY : src/systemthread.cpp.obj

src/systemthread.i: src/systemthread.cpp.i
.PHONY : src/systemthread.i

# target to preprocess a source file
src/systemthread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/systemthread.cpp.i
.PHONY : src/systemthread.cpp.i

src/systemthread.s: src/systemthread.cpp.s
.PHONY : src/systemthread.s

# target to generate assembly for a file
src/systemthread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/systemthread.cpp.s
.PHONY : src/systemthread.cpp.s

src/systemthread_FEcommand.obj: src/systemthread_FEcommand.cpp.obj
.PHONY : src/systemthread_FEcommand.obj

# target to build an object file
src/systemthread_FEcommand.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/systemthread_FEcommand.cpp.obj
.PHONY : src/systemthread_FEcommand.cpp.obj

src/systemthread_FEcommand.i: src/systemthread_FEcommand.cpp.i
.PHONY : src/systemthread_FEcommand.i

# target to preprocess a source file
src/systemthread_FEcommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/systemthread_FEcommand.cpp.i
.PHONY : src/systemthread_FEcommand.cpp.i

src/systemthread_FEcommand.s: src/systemthread_FEcommand.cpp.s
.PHONY : src/systemthread_FEcommand.s

# target to generate assembly for a file
src/systemthread_FEcommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/systemthread_FEcommand.cpp.s
.PHONY : src/systemthread_FEcommand.cpp.s

src/trafficsignal.obj: src/trafficsignal.cpp.obj
.PHONY : src/trafficsignal.obj

# target to build an object file
src/trafficsignal.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/trafficsignal.cpp.obj
.PHONY : src/trafficsignal.cpp.obj

src/trafficsignal.i: src/trafficsignal.cpp.i
.PHONY : src/trafficsignal.i

# target to preprocess a source file
src/trafficsignal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/trafficsignal.cpp.i
.PHONY : src/trafficsignal.cpp.i

src/trafficsignal.s: src/trafficsignal.cpp.s
.PHONY : src/trafficsignal.s

# target to generate assembly for a file
src/trafficsignal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/trafficsignal.cpp.s
.PHONY : src/trafficsignal.cpp.s

src/udpthread.obj: src/udpthread.cpp.obj
.PHONY : src/udpthread.obj

# target to build an object file
src/udpthread.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/udpthread.cpp.obj
.PHONY : src/udpthread.cpp.obj

src/udpthread.i: src/udpthread.cpp.i
.PHONY : src/udpthread.i

# target to preprocess a source file
src/udpthread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/udpthread.cpp.i
.PHONY : src/udpthread.cpp.i

src/udpthread.s: src/udpthread.cpp.s
.PHONY : src/udpthread.s

# target to generate assembly for a file
src/udpthread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/udpthread.cpp.s
.PHONY : src/udpthread.cpp.s

src/vehicle.obj: src/vehicle.cpp.obj
.PHONY : src/vehicle.obj

# target to build an object file
src/vehicle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/vehicle.cpp.obj
.PHONY : src/vehicle.cpp.obj

src/vehicle.i: src/vehicle.cpp.i
.PHONY : src/vehicle.i

# target to preprocess a source file
src/vehicle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/vehicle.cpp.i
.PHONY : src/vehicle.cpp.i

src/vehicle.s: src/vehicle.cpp.s
.PHONY : src/vehicle.s

# target to generate assembly for a file
src/vehicle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LANGUAGES.dir\build.make CMakeFiles/LANGUAGES.dir/src/vehicle.cpp.s
.PHONY : src/vehicle.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... LANGUAGES_autogen
	@echo ... LANGUAGES_autogen_timestamp_deps
	@echo ... LANGUAGES
	@echo ... LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.obj
	@echo ... LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.i
	@echo ... LANGUAGES_autogen/UVLADIE3JM/qrc_resim_resource.s
	@echo ... LANGUAGES_autogen/mocs_compilation.obj
	@echo ... LANGUAGES_autogen/mocs_compilation.i
	@echo ... LANGUAGES_autogen/mocs_compilation.s
	@echo ... src/agent.obj
	@echo ... src/agent.i
	@echo ... src/agent.s
	@echo ... src/agent_control.obj
	@echo ... src/agent_control.i
	@echo ... src/agent_control.s
	@echo ... src/agent_hazardidentification.obj
	@echo ... src/agent_hazardidentification.i
	@echo ... src/agent_hazardidentification.s
	@echo ... src/agent_move.obj
	@echo ... src/agent_move.i
	@echo ... src/agent_move.s
	@echo ... src/agent_perception.obj
	@echo ... src/agent_perception.i
	@echo ... src/agent_perception.s
	@echo ... src/agent_recognition.obj
	@echo ... src/agent_recognition.i
	@echo ... src/agent_recognition.s
	@echo ... src/agent_riskevaluation.obj
	@echo ... src/agent_riskevaluation.i
	@echo ... src/agent_riskevaluation.s
	@echo ... src/agent_route_management.obj
	@echo ... src/agent_route_management.i
	@echo ... src/agent_route_management.s
	@echo ... src/caldistributethread.obj
	@echo ... src/caldistributethread.i
	@echo ... src/caldistributethread.s
	@echo ... src/configwindow.obj
	@echo ... src/configwindow.i
	@echo ... src/configwindow.s
	@echo ... src/eventmanager.obj
	@echo ... src/eventmanager.i
	@echo ... src/eventmanager.s
	@echo ... src/gltransform3d.obj
	@echo ... src/gltransform3d.i
	@echo ... src/gltransform3d.s
	@echo ... src/graphiccanvas.obj
	@echo ... src/graphiccanvas.i
	@echo ... src/graphiccanvas.s
	@echo ... src/logoutputthread.obj
	@echo ... src/logoutputthread.i
	@echo ... src/logoutputthread.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/mainwindow.obj
	@echo ... src/mainwindow.i
	@echo ... src/mainwindow.s
	@echo ... src/networkdrivecheck.obj
	@echo ... src/networkdrivecheck.i
	@echo ... src/networkdrivecheck.s
	@echo ... src/randomgenerator.obj
	@echo ... src/randomgenerator.i
	@echo ... src/randomgenerator.s
	@echo ... src/resim.obj
	@echo ... src/road.obj
	@echo ... src/road.i
	@echo ... src/road.s
	@echo ... src/road_path_calc.obj
	@echo ... src/road_path_calc.i
	@echo ... src/road_path_calc.s
	@echo ... src/scenario.obj
	@echo ... src/scenario.i
	@echo ... src/scenario.s
	@echo ... src/simulationmanager.obj
	@echo ... src/simulationmanager.i
	@echo ... src/simulationmanager.s
	@echo ... src/system_snapshot.obj
	@echo ... src/system_snapshot.i
	@echo ... src/system_snapshot.s
	@echo ... src/systemthread.obj
	@echo ... src/systemthread.i
	@echo ... src/systemthread.s
	@echo ... src/systemthread_FEcommand.obj
	@echo ... src/systemthread_FEcommand.i
	@echo ... src/systemthread_FEcommand.s
	@echo ... src/trafficsignal.obj
	@echo ... src/trafficsignal.i
	@echo ... src/trafficsignal.s
	@echo ... src/udpthread.obj
	@echo ... src/udpthread.i
	@echo ... src/udpthread.s
	@echo ... src/vehicle.obj
	@echo ... src/vehicle.i
	@echo ... src/vehicle.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

